config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Sub < ApplicationRecord

  validates :title, :description, :user_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    class_name: :User,
    foreign_key: :user_id

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  attr_reader :password

  validates :username, presence: { message: "can\'t be blank" }
  validates :password_digest, presence: { message: "Password can\'t be blank" }
  validates :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token

  has_many :subs, inverse_of: 'moderator', dependent: :destroy

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :require_login

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  private

  def require_login
    unless current_user
      flash[:alert] = "You must be logged in to view this resource."
      redirect_to new_session_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:alert] = 'Invalid credentials.'
      render :new, status: :unauthorized
    end
  end

  def destroy
    logout!
    render :new
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show, :edit]
  before_action :require_moderator, only: [:edit]

  def index
    render :index
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:alert] = 'One or more paramaters missing.'
      render :new, status: :unprocessable_entity
    end
  end

  def new
    render :new
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    if @sub
      render :edit
    else
      if current_user
        flash.now[:alert] = "Sub not found. Try again with valid sub id."
        render :index, status: :not_found
      else
        flash.now[:alert] = "Sub not found. Try again with valid sub id and moderator status."
        render :index, status: :not_found
      end
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    if @sub
      render :show
    else
      flash.now[:alert] = 'No such sub!'
      render :index, status: :not_found
    end
  end

  def update

  end

  def destroy

  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator
    @sub = Sub.find_by(id: params[:id])
    if @sub && @sub.moderator && @sub.moderator != current_user
      flash.now[:alert] = 'Edit access requires moderator status.'
      render :index, status: :unauthorized
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    '<input type="hidden" name="authenticity_token" value="#{form_authenticity_token}" />'.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_user.nil? %>
      <ul>
        <li>Current user: <%= current_user.username %></li>
        <li><%= button_to 'Logout', session_url, method: :delete %></li>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_users_form.html.erb
<% path = (source == :session ? session_url : users_url) %>
<% message = (source == :session ? "Log in" : "Register") %>

<form class="" action="<%= path %>" method="post">
  <%= auth_token %>
  <label for="username">Username</label>
  <input type="text" name="user[username]" value="" id="username">

  <label for="password">Password</label>
  <input type="password" name="user[password]" value="" id="password">

  <input type="submit" name="" value="<%= message %>">

</form>

app/views/subs/edit.html.erb
<h2>edit a sub!</h2>

app/views/subs/index.html.erb
<h2>All the subs!</h2>

app/views/subs/new.html.erb
<h2>Create a sub!</h2>

app/views/subs/show.html.erb
<h2>all about this sub!</h2>

app/views/users/new.html.erb
<h2>Register</h2>

<% if flash[:errors].present? %>
  <% flash[:errors].each do |error| %>
    <div class="flash-display">
      <%= error %>
    </div>
  <% end %>
<% end %>

<%= render 'shared/users_form', source: :user %>

<br>
<br>

Already registered? <%= button_to 'Log in', new_session_url, method: :get %>

app/views/users/show.html.erb
<h2>Profile for <%= @user.username %></h2>